# Generated by Django 6.0 on 2025-12-08 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board', models.JSONField(default=dict)),
                ('current_player', models.IntegerField(default=1)),
                ('phase', models.CharField(default='move', max_length=10)),
                ('last_moved_piece', models.JSONField(blank=True, null=True)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
